name: After merging PR

on:
  push:
    branches:
      - master
      - main
      - build_test

  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  devel-tag-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install Build deps
      run: |
        sudo apt install -y libyaml-dev
    - name: Generate
      run: |
        cd docs && make site-build-prod
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/output
